In [1]:
import numpy as np

In [2]:
print(np.version.version)

1.11.1


使用numpy.arange方法

In [3]:
print(np.array((1.2,2,3,4), dtype=np.int32))

[1 2 3 4]


在从1到3中产生9个数：

In [4]:
print(np.linspace(1,3,9))

[ 1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.  ]


使用numpy.arange方法

In [5]:
print(np.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [6]:
a = np.ones((2,2))
b = np.eye(2)
print(a)
print(b)
print(np.vstack((a,b)))

[[ 1.  1.]
 [ 1.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  0.]
 [ 0.  1.]]
